package com.damianhoward.stocks.analysis.us.analysis.repository;

import com.damianhoward.stocks.analysis.us.analysis.domain.AnalysisStock;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIf;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.annotation.Transactional;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

/**
 * Exercises the AnalysisStock entity against the real Flyway-created PostgreSQL
 * schema in a Testcontainer. Catches mismatches between JPA mappings and the
 * migration SQL (e.g. the id-type mismatch caught in the original bug).
 *
 * Each test is transactional so changes roll back between tests.
 */
@Testcontainers
@SpringBootTest
@ActiveProfiles("integration")
@Transactional
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_CLASS)
@EnabledIf(
        value = "com.damianhoward.stocks.testutil.DockerAvailable#check",
        disabledReason = "Docker is not available")
class AnalysisRepositoryIntegrationTest {

    @Container
    @ServiceConnection
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:17-alpine");

    @Autowired
    private AnalysisRepository analysisRepository;

    @Test
    void savedStockRoundTripsThroughFlywayCreatedSchema() {
        LocalDate today = LocalDate.now();
        AnalysisStock stock = AnalysisStock.builder()
                .date(today)
                .zacksCode("AAPL")
                .zacksCompany("Apple Inc.")
                .company("Apple")
                .currency("USD")
                .marketCap(new BigDecimal("3000000000000"))
                .price(new BigDecimal("180.50"))
                .targetPrice(new BigDecimal("200.00"))
                .recommendationRating(new BigDecimal("2.1"))
                .nextYearPEG(new BigDecimal("1.42"))
                .category("growth")
                .build();

        AnalysisStock saved = analysisRepository.save(stock);
        assertNotNull(saved.getId(), "id should be generated by the sequence");

        Set<AnalysisStock> byDate = analysisRepository.findByDate(today);
        assertEquals(1, byDate.size());
        AnalysisStock found = byDate.iterator().next();
        assertEquals("AAPL", found.getZacksCode());
        assertEquals(0, new BigDecimal("180.50").compareTo(found.getPrice()));
        assertEquals(0, new BigDecimal("2.1").compareTo(found.getRecommendationRating()));
        assertEquals(0, new BigDecimal("1.42").compareTo(found.getNextYearPEG()));
    }

    @Test
    void deleteByDateRemovesOnlyThatDay() {
        LocalDate today = LocalDate.now();
        LocalDate yesterday = today.minusDays(1);

        analysisRepository.save(AnalysisStock.builder().date(today).zacksCode("A").category("c").build());
        analysisRepository.save(AnalysisStock.builder().date(today).zacksCode("B").category("c").build());
        analysisRepository.save(AnalysisStock.builder().date(yesterday).zacksCode("C").category("c").build());
        analysisRepository.flush();

        analysisRepository.deleteByDate(today);

        assertEquals(0, analysisRepository.findByDate(today).size());
        assertEquals(1, analysisRepository.findByDate(yesterday).size());
    }
}
